



```{r}
library(tidyverse)
library(googlesheets)
library(rmapshaper)
library(rvest)
library(sf)
library(sp)
library(GADMTools)
```

```{r}
my_sf <- st_read("gadm36_ZAF_shp/gadm36_ZAF_1.shp")
```




prov <- c("Free State", "Gauteng", "Western Cape", "Northern Cape", "Mpumalanga", "KwaZulu-Natal", "Eastern Cape", "Limpopo")



```{r}
#sa_wrapper = gadm_sf.loadCountries("ZAF", level = 1, basefile = "./")

my_spdf = as(my_sf, "Spatial")
class(my_spdf)

str(my_spdf, max.level = 2)

glimpse(my_spdf@data)
```


```{r}

sa_sf = st_as_sf(my_spdf)
class(sa_sf)
```


```{r}
head(sa_sf, 4)
```

```{r}

```

```{r}

```


ind_sf <- ind_sf %>%
  mutate(my_area = as.vector(my_area), 
         gdp_density_usd_km2 = as.vector(gdp_density_usd_km2))

original_geometry <- st_geometry(ind_sf)

library(rmapshaper)
simp_sf <- ms_simplify(ind_sf, keep = 0.01, keep_shapes = TRUE)
simple_geometry <- st_geometry(simp_sf)

par(mfrow = c(1,2))
plot(original_geometry, main = "Original Geometry")
plot(simple_geometry, main = "Simple Geometry")


